### ISSUE TITLE
似乎没有docker image

### ISSUE THREAD

**Issue by ghost** [shadowsocks/simple-obfs#196]
如题，从docker镜像官网找不到，用docker管理实在太方便了，如果能支持就好了。

**Comment by dy2898** [comment]
docker内的fastopen不会生效。服务器cat /proc/sys/net/ipv4/tcp_fastopen 结果是3，docker容器结果是1

**Comment by zgist** [comment]
可以试试**docker-compose.yml**

```
version: '3'

services:
    shadowsocks:
        container_name: shadowsocks
        image: gists/shadowsocks-libev
        ports:
            - "8443:8388/udp"
        networks:
            overlay:
        environment:
          - PASSWORD=passowrd
          - METHOD=chacha20-ietf-poly1305
        restart: always

      simple-obfs:
        container_name: obfs
        image: gists/simple-obfs
        ports:
            - "8443:8388/tcp"
        environment:
            - FORWARD=shadowsocks:8388
        networks:
            overlay:
        restart: always

networks:
    overlay:
        driver: bridge
```
